- name: Copy files
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
  loop:
    - docker-compose.yaml
    - datasource.yaml
    - dashboards.yaml

- name: Render prometheus.yml
  become: yes
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ ansible_user_dir }}/prometheus.yml"

- name: Ensure dashboards dir
  become: yes
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/dashboards"
    state: directory

- name: Copy dashboards
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/dashboards/{{ item | basename }}"
  with_fileglob:
    - "*.json"

- name: Create and start services
  become: yes
  community.docker.docker_compose:
    project_src: "{{ ansible_user_dir }}"
