emqx_version_family: "5"
home_dir: /opt/monitoring

prometheus_config_dir: /etc/prometheus

prometheus_global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 1s

prometheus_remote_write: []
# prometheus_remote_write:
#   - url: https://dev.kausal.co/prom/push
#     basic_auth:
#       password: FOO

prometheus_remote_read: []
# prometheus_remote_read:
#   - url: https://prometheus.demo.do.prometheus.io:9201/read
#     basic_auth:
#       password: FOO

prometheus_node_exporter_targets: []
prometheus_emqx_targets: []

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "pushgateway"
    honor_labels: true
    scrape_interval: 1s
    static_configs:
      - targets:
        - "localhost:9091"
  - job_name: 'emqx'
    metrics_path: "{{ (emqx_version_family == 5) | ternary('/api/v5/prometheus/stats', '/api/v4/emqx_prometheus') }}"
    scrape_interval: 1s
    honor_labels: true
    static_configs:
      - targets: "{{ groups['emqx'] | map('regex_replace', '$', ':18083') | list }}"
        labels:
          cluster: perftest
          from: emqx
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "instance"
        regex: (.*):.*
        replacement: $1
  - job_name: 'emqx-exporter'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: "{{ groups['emqx'] | map('regex_replace', '$', ':8085') | list }}"
        labels:
          cluster: perftest
          from: exporter
  - job_name: "node"
    static_configs:
      - targets: "{{ groups['all'] | map('regex_replace', '$', ':9100') | list }}"
