- name: Ensure data directory
  become: yes
  ansible.builtin.file:
    path: "{{ emqx_data_dir }}"
    state: directory
    mode: 0755
    owner: emqx
    group: emqx

- name: Ensure data directory for durable storage
  when: emqx_durable_storage_data_dir is defined
  become: yes
  ansible.builtin.file:
    path: "{{ emqx_durable_storage_data_dir }}"
    state: directory
    mode: 0755
    owner: emqx
    group: emqx

- name: Ensure linked directory sources
  when: emqx_link_dirs is defined
  become: yes
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    mode: 0755
    owner: emqx
    group: emqx
  with_items: "{{ emqx_link_dirs }}"
  tags:
    - config

- name: Ensure linked directory targets
  when: emqx_link_dirs is defined
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: link
    src: "{{ item.src }}"
    mode: 0755
    owner: emqx
    group: emqx
  with_items: "{{ emqx_link_dirs }}"
  tags:
    - config

- name: Render /etc/emqx/emqx.conf
  become: yes
  ansible.builtin.template:
    src: emqx.conf.j2
    dest: /etc/emqx/emqx.conf
    mode: '0644'
  register: _emqx_conf
  tags:
    - config

- name: Render acl.conf
  become: yes
  ansible.builtin.template:
    src: acl.conf.j2
    dest: /etc/emqx/acl.conf
    mode: '0644'

- name: Render vm.args
  become: yes
  ansible.builtin.template:
    src: vm.args.j2
    dest: /etc/emqx/vm.args
    mode: '0644'
  register: _emqx_vm_args

- name: Render boostrap api keys file
  become: yes
  ansible.builtin.template:
    src: bootstrap-api.j2
    dest: "{{ emqx_api_key_bootstrap_file }}"
    mode: '0644'
  register: _bootstrap_api

- name: Render environment overrides
  become: yes
  ansible.builtin.template:
    src: env.j2
    dest: /etc/emqx/env
    mode: '0644'
  register: _env

- name: Create a directory for systemd service override
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/emqx.service.d
    state: directory
    mode: 0755

- name: Render systemd service override file
  become: yes
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/emqx.service.d/override.conf
    mode: '0644'
  register: _override

- name: Copy certificates
  become: yes
  ansible.builtin.copy:
    src: "/etc/ssl/certs/emqx/{{ item }}"
    dest: "/etc/emqx/certs/"
    remote_src: yes
    mode: '0644'
  with_items:
    - "cacert.pem"
    - "cert.pem"
    - "key.pem"
    - "client-cert.pem"
    - "client-key.pem"
