- include_tasks: install-repo.yml
  when: emqx_package_download_url == '' and emqx_package_file_path == ''

- name: Upload package
  when: emqx_package_file_path != ''
  ansible.builtin.copy:
    src: "{{ emqx_package_file_path }}"
    dest: "/tmp/emqx.{{ (ansible_os_family == 'Debian') | ternary('deb', 'rpm') }}"

- name: Install emqx
  become: yes
  when: ansible_os_family == 'Debian' and emqx_package_download_url != ''
  ansible.builtin.apt:
    deb: emqx_package_download_url
    state: present
    update_cache: yes

- name: Install emqx
  become: yes
  when: ansible_os_family == 'Debian' and emqx_package_file_path != ''
  ansible.builtin.apt:
    deb: /tmp/emqx.deb
    state: present
    update_cache: yes

- name: Install emqx
  become: yes
  when: ansible_os_family == 'RedHat' and emqx_package_download_url != ''
  ansible.builtin.yum:
    name: emqx_package_download_url
    state: present

- name: Install emqx
  become: yes
  when: ansible_os_family == 'RedHat' and emqx_package_file_path != ''
  ansible.builtin.yum:
    name: /tmp/emqx.rpm
    state: present

- name: Install emqx
  become: yes
  when: emqx_package_download_url == '' and emqx_package_file_path == ''
  ansible.builtin.apt:
    name: emqx
    state: present
    update_cache: yes

- name: Render /etc/emqx/emqx.conf
  become: yes
  ansible.builtin.template:
    src: emqx.conf.j2
    dest: /etc/emqx/emqx.conf
    mode: '0644'
  register: _emqx_conf

- name: Render boostrap api keys file
  become: yes
  ansible.builtin.template:
    src: bootstrap-api.j2
    dest: "{{ emqx_api_key_bootstrap_file }}"
    mode: '0644'
  register: _bootstrap_api

- name: Render environment overrides
  become: yes
  ansible.builtin.template:
    src: env.j2
    dest: /etc/emqx/env
    mode: '0644'
  register: _env

- name: Create a directory for systemd service override
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/emqx.service.d
    state: directory
    mode: 0755

- name: Render systemd service override file
  become: yes
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/emqx.service.d/override.conf
    mode: '0644'
  register: _override

- name: Start emqx
  become: yes
  ansible.builtin.systemd:
    name: emqx.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart emqx
  become: yes
  when: _emqx_conf.changed or _bootstrap_api.changed or _env.changed or _override.changed
  ansible.builtin.systemd:
    name: emqx.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Start emqx
  become: yes
  ansible.builtin.systemd:
    name: emqx.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for emqx to start listening on port 1883
  ansible.builtin.wait_for:
    port: 1883
    host: localhost
    delay: 5
    timeout: 60
    state: started

- name: Wait until /status responds with 200
  ansible.builtin.uri:
    url: "http://127.0.0.1:18083/status"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 12
  delay: 5
