- include_tasks: install-git.yml
  when: emqx_install_source == 'git'
- include_tasks: install-package.yml
  when: emqx_install_source == 'package'
- include_tasks: perf.yml
  when: emqx_enable_perf
  tags: [perf]
- include_tasks: configure.yml
  tags: [config]
- include_tasks: service.yml
- include_tasks: scripts.yml
- include_tasks: alloy.yml
  when: loki_url is defined and loki_url != ''
