- name: Create directory for scripts
  become: yes
  ansible.builtin.file:
    path: /opt/emqx
    state: directory
    mode: '0755'
    owner: emqx
    group: emqx

- name: Copy scripts
  become: yes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: /opt/emqx/
    mode: '0755'
    owner: emqx
    group: emqx
  loop: "{{ emqx_scripts }}"

- name: Run scripts
  become: yes
  become_user: emqx
  run_once: yes
  environment: "{{ emqx_script_env }}"
  ansible.builtin.command: "/opt/emqx/{{ item | basename }}"
  loop: "{{ emqx_scripts }}"
