- name: Restart emqx
  become: yes
  when: _emqx_conf.changed or _bootstrap_api.changed or _env.changed or _override.changed
  ansible.builtin.systemd:
    name: emqx.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Ensure emqx is started
  become: yes
  ansible.builtin.systemd:
    name: emqx.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for emqx to start listening on port 1883
  ansible.builtin.wait_for:
    port: 1883
    host: localhost
    delay: 5
    timeout: 60
    state: started

- name: Wait until /status responds with 200
  ansible.builtin.uri:
    url: "http://127.0.0.1:18083/status"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 12
  delay: 5
