- name: Get latest emqttb release
  when: emqttb_options.version == 'latest' and emqttb_options.package_download_url == '' and emqttb_options.package_file_path == ''
  uri:
    url: https://api.github.com/repos/emqx/emqttb/releases/latest
    body_format: json
    return_content: yes
  register: github_response

- name: Parse JSON response to get the latest version tag
  when: emqttb_options.version == 'latest' and emqttb_options.package_download_url == '' and emqttb_options.package_file_path == ''
  set_fact:
    emqttb_version: "{{ github_response.json.tag_name }}"

- name: Set emqttb_version to the specified version
  when: emqttb_options.version != 'latest' and emqttb_options.package_download_url == '' and emqttb_options.package_file_path == ''
  set_fact:
    emqttb_version: "{{ emqttb_options.version }}"

- name: Download emqttb package
  when: emqttb_options.package_download_url != ''
  ansible.builtin.get_url:
    url: emqttb_options.package_download_url
    dest: /tmp/emqttb.tar.gz
    mode: '0644'

- name: Download emqttb package
  when: emqttb_options.package_download_url == '' and emqttb_options.package_file_path == ''
  ansible.builtin.get_url:
    url: "https://github.com/emqx/emqttb/releases/download/{{ emqttb_version }}/emqttb-{{ emqttb_version | regex_replace('^v', '') }}-{{ ansible_distribution | lower }}{{ ansible_distribution_version }}-{{ deb_architecture_map[ansible_architecture] }}-quic.tar.gz"
    dest: "/tmp/emqttb.tar.gz"
    mode: '0644'

- name: Upload package
  when: emqttb_options.package_file_path != ''
  ansible.builtin.copy:
    src: "{{ emqttb_options.package_file_path }}"
    dest: "/tmp/emqttb.tar.gz"

- name: Create emqttb system user
  become: yes
  ansible.builtin.user:
    name: emqttb
    shell: /bin/bash
    system: yes
    createhome: yes
    home: "{{ emqttb_options.home_dir }}"

- name: Install system packages
  become: yes
  ansible.builtin.package:
    name:
      # This is needed so that the unarchive operation can succeed at setting permissions.
      - acl
    state: present

- name: Unarchive emqttb
  become: yes
  become_user: emqttb
  ansible.builtin.unarchive:
    src: "/tmp/emqttb.tar.gz"
    dest: "{{ emqttb_options.home_dir }}"
    copy: no
    mode: '0755'

- name: Render emqttb systemd unit file
  become: yes
  ansible.builtin.template:
    src: emqttb.service.j2
    dest: /etc/systemd/system/emqttb.service
    mode: '0644'

- name: Create /etc/emqttb directory
  become: yes
  ansible.builtin.file:
    path: /etc/emqttb
    state: directory
    mode: '0755'

- name: Render emqttb env file
  become: yes
  ansible.builtin.template:
    src: env.j2
    dest: /etc/emqttb/env
    mode: '0644'

- name: Enable service
  become: yes
  ansible.builtin.systemd_service:
    name: emqttb
    daemon_reload: yes
    enabled: yes
