services:
  loki:
    image: grafana/loki:3.5.1
    user: 10001:10001
    command:
      - '-config.file=/etc/loki/config.yaml'
      - '-target=all'
    ports:
      - 3100:3100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./loki.yaml:/etc/loki/config.yaml
      - ./loki-data:/loki

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/data

  pushgateway:
    image: prom/pushgateway:v1.11.1
    container_name: pushgateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/metrics"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - 9091:9091
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/node-exporter-multi-server.json
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=EMQX
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards
