{
 "title": "emqttb",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of workers per group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "emqttb_group_n_workers{}", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Client spawn rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(emqttb_group_n_workers{}[5s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Published messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_published_messages{}[5s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Received messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(emqttb_received_messages{}[5s])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Number of pending operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "emqttb_group_n_pending", "legendFormat": "{{group}}/{{operation}}" }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "emqttb_group_op_time", "legendFormat": "{{group}}/{{operation}}" }
   ]
  },
  {
   "title": "Autorate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_autorate_rate", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Autorate control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emqttb_autorate_control", "legendFormat": "{{id}}/{{term}}" }
   ]
  },
  {
   "title": "Persistent session throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "emqttb_pers_sess_pub_throughput_sum{}"
    }
   ]
  }
 ]
}