version: "3.8"
services:
  emqx-exporter:
    image: emqx/emqx-exporter:0.2.3
    container_name: emqx-exporter
    network_mode: host
    volumes:
      - ./emqx-exporter.config.yaml:/usr/local/emqx-exporter/bin/config.yaml
