locust_options:
  version: latest
  web_port: 8080
  home_dir: "/var/lib/locust"
  plan_entrypoint: locustfile.py
  client_prefix_list: "a,b,c"
  payload_size: 1024
  unsubscribe_client_batch_size: 100

locust_entrypoint: "{{ locust_options.home_dir }}/{{ locust_options.plan_entrypoint }}"
