- name: Download script from https://get.docker.com
  become: yes
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /opt/get-docker.sh
    mode: '0755'

- name: Run get-docker.sh
  become: yes
  ansible.builtin.shell: /opt/get-docker.sh

- name: Add user to docker group
  become: yes
  ansible.builtin.user:
    append: true
    name: "{{ ansible_user }}"
    groups: docker

- name: Install python pip packages
  become: yes
  ansible.builtin.pip:
    name:
      - docker==6.1.3
      - docker-compose
    state: present
