- hosts: all
  pre_tasks:
    - name: Store available ip addresses
      ansible.builtin.set_fact:
        available_ip_addresses: "{{ ansible_all_ipv4_addresses }}"
  tasks:
    - name: Add entries to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "{{ item }}"
        line: "{{ hostvars[item].private_ip }}\t{{ item }}"
      become: yes
      loop: "{{ ansible_play_hosts }}"

    - name: Add entries to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "{{ inventory_hostname }}"
        line: "127.0.0.1\t{{ inventory_hostname }}"
      become: yes
